### ISSUE TITLE
Revisões no Help do Plugin

### ISSUE THREAD

**Issue by EdRolla** [visualworks/freez-recipes#28]
Dei falta do link da lista das receitas (http://homechefs.com.br/assinantes/receitas/) no help.

Falando no Help, teria como a gente migrar esse botão de **[ configurações > Freez Recipes ]** para **[ Receitas > Help ]**?
A galera que opera não é muito ninja e isso vai fazer diferença...

**Comment by henriquemattos** [comment]
O link está lá, mas esse seu tema precisaria ser trabalhado. Veja como respondi a outra issue sobre a lista de receitas com link, checkbox, paginação, filtros, etc...

Sim, vou migrar, mas é tosco :P haha Mas vou fazer.

**Comment by EdRolla** [comment]
Não tem problema ser tosco não.
A ideia é ser apenas uma anotação à mão. 
Depois, se for o caso, me diz qual arquivo mexer e eu dou um tapa nele...
