### ISSUE TITLE
Layouts das páginas "Lista de Receitas" e "Detalhes da Receita"

### ISSUE THREAD

**Issue by EdRolla** [visualworks/freez-recipes#29]
_Nota: para facilitar a comunicação, estou chamando de "Lista de Receitas" a página que lista todas as receitas automaticamente (http://homechefs.com.br/assinantes/receitas/) e a "Detalhes da Receita" a página de uma receita qualquer (ex.: http://homechefs.com.br/assinantes/receitas/creme-de-morango-gelado-4-porcoes/)._

Precisamos revisar estes layouts para ficarem como havíamos combinado.
![print lista de receitas](https://user-images.githubusercontent.com/2001215/34044089-ca6cc440-e18a-11e7-916c-dba2385b285c.png)

Lembrando que teremos 4 layouts possíveis, um de acordo com cada linha de cardápio.
(não tenho certeza do que combinamos/decidimos a respeito disso)

**Comment by henriquemattos** [comment]
Ed, eu não vou criar a página do template. Você pode criar uma página no admin do WP e colocar o shortcode para listar as receitas lá. Eu vou gerar uma paginação ainda, que é o que falta. O template não é parte do plugin, é parte do WP/Tema e isso você pode criar até dinamicamente usando seu plugin de estilos para páginas.

Cria uma página chamada "Receitas", coloca o shortcode no conteúdo e veja sua página de lista de receitas. Aplique os estilos que quiser no CSS.

Pelo o que estou lembrando e entendendo, você precisa de um shortcode para categorias então.

**Comment by EdRolla** [comment]
Bem lembrado, man!
Era isso mesmo.
