### ISSUE TITLE
Receita mãe nos documentos

### ISSUE THREAD

**Issue by EdRolla** [visualworks/freez-recipes#30]
Dei falta da receita que origina o ingrediente na tabela de ingredientes.
Lembra que falamos disso?

Segue o link para verificar: http://homechefs.com.br/assinantes/temp/

Inclusive isso resultava que a gente precisava restringir o número do receitas que selecionadas (5 no max). que será o próximo issue que vou abrir para ficar mais organizado....

**Comment by henriquemattos** [comment]
Conforme falei no e-mail, isso não será viável em termos de layout e estrutura. Ingredientes como Sal, Ovos, Azeite e outros que são usados em mais de duas receitas viram o caos visualmente, além de tornarem o processo de criação do PDF lento, podendo gerar falhas.

**Comment by henriquemattos** [comment]
Chefe, tem certeza que é isso que o cara quer? Lista de receitas que originaram o ingrediente na lista? Estou comitando isso agora...

![Lista de Ingredientes com receitas originárias](https://user-images.githubusercontent.com/2782214/34408001-9b22aae2-ebc1-11e7-9b85-65f9370822bf.png)

**Comment by henriquemattos** [comment]
ps.: No PDF ficou ainda pior, sem contar que passou a ter 3 páginas 👎 . Segue screenshot:

<img width="1065" alt="screen shot 2017-12-28 at 11 30 54" src="https://user-images.githubusercontent.com/2782214/34408187-9a9643a8-ebc2-11e7-95a0-3f127307165c.png">

**Comment by EdRolla** [comment]
cara, acho que não tem com ser diferente disso.
e a parada de aumentar mt o tamanho da receita (# de páginas), ele estava ciente e quis seguir em frente...
