### ISSUE TITLE
Restrição de 5 receitas no máximo

### ISSUE THREAD

**Issue by EdRolla** [visualworks/freez-recipes#31]
Na listagem de receitas, precisamos restringir o número de receitas que podem ser selecionadas (5 no máximo) ou o número de receitas que originam um determinado ingredientes ficará muito grande e os documentos virarão uma balburdia. 
http://homechefs.com.br/assinantes/temp/

Nota: mt capaz de ele se arrepender disso (eu acho um tiro no pé), mas insistiu. 
Então, procure deixar uma forma fácil de desfazer isso pois é mais um update que rola tranquilo.

**Comment by henriquemattos** [comment]
Ok. Vou fazer
