### ISSUE TITLE
Paginação

### ISSUE THREAD

**Issue by EdRolla** [visualworks/freez-recipes#32]
Mestre, coloquei o seguinte shortcode, mas não rolou paginação.
[freezrecipes checkbox="true" link="true" order="ASC" orderby="title" perpage="10"]

Resultado: http://homechefs.com.br/assinantes/temp/

Será que to fazendo alguma coisa errada?

**Comment by henriquemattos** [comment]
Sim, eu te falei no e-mail que não vai rolar paginação no shortcode. Vai ter que fazer uma página no tema para lidar com a paginação.

**Comment by EdRolla** [comment]
Eita... não tinha entendido isso...

Diz criar uma página física ou através daquele pagebuilder do tema?

**Comment by henriquemattos** [comment]
Para que ocorra a paginação, tem que criar uma página "física" no PHP do tema mesmo. Através do pagebuilder você pode usar o shortcode e filtrar por categorias, por exemplo, mas a paginação não aparece. Tentei de inúmeras formas, pesquisei bastante e realmente não consegui fazer. A função nativa do WordPress para paginação só funciona com o $wp_query que não funciona corretamente com Custom Post Type. Neste caso, ou rola a paginação ou rola o filtro pro categoria. Os dois juntos não rolou.
