### ISSUE TITLE
Erro 500 ao tentar gerar o pdf.

### ISSUE THREAD

**Issue by EdRolla** [visualworks/freez-recipes#33]
Desde o último release, ao tentar gerar o pdf, um erro 500 (de servidor) é retornado.

Alguma forma (log?) de eu debugar para vc e te retornar mais detalhes?

**Comment by henriquemattos** [comment]
Provavelmente no error.log ou error_log padrão para seu host, mas eu pude ver aqui que ele está redirecionando para a página de login do WordPress. Não reproduzo o erro 500, mas vejo que está com algum problema. Vou debugar aqui e retorno com a resolução voando!!!

**Comment by EdRolla** [comment]
Analisei os arquivos de log e nada... :(
